//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demolite.Discord.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoggingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demolite.Discord.Core.Resources.LoggingResource", typeof(LoggingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to message.
        /// </summary>
        public static string Body_Actions_LinkToMessage {
            get {
                return ResourceManager.GetString("Body_Actions_LinkToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to join: &lt;#{0}&gt;.
        /// </summary>
        public static string Body_Actions_LinkToVoiceChannel {
            get {
                return ResourceManager.GetString("Body_Actions_LinkToVoiceChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message by user {0} has been deleted in &lt;#{1}&gt;..
        /// </summary>
        public static string Body_MessageDeleted {
            get {
                return ResourceManager.GetString("Body_MessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors with retrieving the message.
        /// </summary>
        public static string Body_MessageDeleted_Errors {
            get {
                return ResourceManager.GetString("Body_MessageDeleted_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message was deleted in &lt;#{0}&gt; but the content could not be retrieved from cache..
        /// </summary>
        public static string Body_MessageDeleted_NotFound {
            get {
                return ResourceManager.GetString("Body_MessageDeleted_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message by user {0} has been edited..
        /// </summary>
        public static string Body_MessageEdited {
            get {
                return ResourceManager.GetString("Body_MessageEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content could not be retrieved from cache..
        /// </summary>
        public static string Body_MessageEdited_NotFound {
            get {
                return ResourceManager.GetString("Body_MessageEdited_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been banned from the server..
        /// </summary>
        public static string Body_UserBanned {
            get {
                return ResourceManager.GetString("Body_UserBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fetch ban reason..
        /// </summary>
        public static string Body_UserBanned_ReasonNotFound {
            get {
                return ResourceManager.GetString("Body_UserBanned_ReasonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} joined the server..
        /// </summary>
        public static string Body_UserJoined {
            get {
                return ResourceManager.GetString("Body_UserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has left the server..
        /// </summary>
        public static string Body_UserLeft {
            get {
                return ResourceManager.GetString("Body_UserLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been timed out for spamming..
        /// </summary>
        public static string Body_UserTimedOut {
            get {
                return ResourceManager.GetString("Body_UserTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice channel {0} has been created..
        /// </summary>
        public static string Body_VoiceCreated {
            get {
                return ResourceManager.GetString("Body_VoiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} has been deleted due to inactivity..
        /// </summary>
        public static string Body_VoiceDeleted {
            get {
                return ResourceManager.GetString("Body_VoiceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions:.
        /// </summary>
        public static string Header_Actions {
            get {
                return ResourceManager.GetString("Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content:.
        /// </summary>
        public static string Header_Content {
            get {
                return ResourceManager.GetString("Header_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message deleted.
        /// </summary>
        public static string Header_MessageDeleted {
            get {
                return ResourceManager.GetString("Header_MessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message edited.
        /// </summary>
        public static string Header_MessageEdited {
            get {
                return ResourceManager.GetString("Header_MessageEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message:.
        /// </summary>
        public static string Header_MessageEdited_NewMessage {
            get {
                return ResourceManager.GetString("Header_MessageEdited_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original message:.
        /// </summary>
        public static string Header_MessageEdited_OriginalMessage {
            get {
                return ResourceManager.GetString("Header_MessageEdited_OriginalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User banned.
        /// </summary>
        public static string Header_UserBanned {
            get {
                return ResourceManager.GetString("Header_UserBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban reason:.
        /// </summary>
        public static string Header_UserBanned_Reason {
            get {
                return ResourceManager.GetString("Header_UserBanned_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User joined.
        /// </summary>
        public static string Header_UserJoined {
            get {
                return ResourceManager.GetString("Header_UserJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account age:.
        /// </summary>
        public static string Header_UserJoined_Age {
            get {
                return ResourceManager.GetString("Header_UserJoined_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User left.
        /// </summary>
        public static string Header_UserLeft {
            get {
                return ResourceManager.GetString("Header_UserLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User timed out.
        /// </summary>
        public static string Header_UserTimedOut {
            get {
                return ResourceManager.GetString("Header_UserTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel created.
        /// </summary>
        public static string Header_VoiceCreated {
            get {
                return ResourceManager.GetString("Header_VoiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel deleted.
        /// </summary>
        public static string Header_VoiceDeleted {
            get {
                return ResourceManager.GetString("Header_VoiceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time open:.
        /// </summary>
        public static string Header_VoiceDeleted_TimeOpen {
            get {
                return ResourceManager.GetString("Header_VoiceDeleted_TimeOpen", resourceCulture);
            }
        }
    }
}
